### ISSUE TITLE
Ditch the license acceptance 

### ISSUE THREAD

**Issue by edyoung** [rjmholt/PSUnixUtilCompleters#9]
IANAL but I don't think it's necessary or useful to make people explicitly agree to the MIT License to install.

**Comment by rjmholt** [comment]
> IANAL but I don't think it's necessary or useful to make people explicitly agree to the MIT License to install.

Yes, someone else pointed this out. It was because `New-ModuleManifest` at the time made this true by default. I believe this is fixed in master, but I was hoping to release this as `Microsoft.PowerShell.UnixCompleters`. See https://github.com/PowerShell/Modules/pull/44.

**Comment by rjmholt** [comment]
Fixed in https://github.com/PowerShell/Modules/pull/44
